spring.application.name=hillcoast-connect
spring.datasource.url=jdbc:mysql://localhost:3306/hillcoast_db
spring.datasource.username=root
spring.datasource.password=lkjh0987
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=8080
spring.security.user.name=gokul
spring.security.user.password=GD@0809
